### ISSUE TITLE
TConstPDoubleArr: [dcc64 Error] MatrixConst.pas(56): E2100 Data type too large: exceeds 2 GB

### ISSUE THREAD

**Issue by ReinierNL** [mikerabat/mrmath#10]
When I try to compile the unit Matrix.pas with Delphi, I get the above mentioned error, on line 56.
It is easy to fix.
Instead of
`  TConstPDoubleArr = Array[0..MaxInt div sizeof(double)] of PDouble;`
it should be
`  TConstPDoubleArr = Array[0..MaxInt div sizeof(double) - 1] of PDouble;`

**Comment by mikerabat** [comment]
Thanks - It is a bit unfortunate since the 32bit compiler (Delphi2010) did not throw an error. I pushed the fix to the repository…Am 22.12.2024 um 15:29 schrieb Reinier Sterkenburg ***@***.***>:﻿
When I try to compile the unit Matrix.pas with Delphi, I get the above mentioned error, on line 56.
It is easy to fix.
Instead of
  TConstPDoubleArr = Array[0..MaxInt div sizeof(double)] of PDouble;
it should be
  TConstPDoubleArr = Array[0..MaxInt div sizeof(double) - 1] of PDouble;

**Comment by mikerabat** [comment]
Fixed as far as I can see.

**Comment by ReinierNL** [comment]
Yeah, a bit funny that the Delphi compiler you used did not flag it. But no big deal.
My daily automatic build tripped on it.
And now it is happy again :-). Thanks, keep up the excellent work!
